name: Build Zephir Binaries (Linux)

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build-linux:
    name: Build Linux Release Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Add target
        run: rustup target add ${{ matrix.target }}

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libssl-dev

      - name: Build release binary
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Archive binary
        run: |
          mkdir -p artifacts
          cp target/${{ matrix.target }}/release/zephir-rs artifacts/zephir-rs-${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: zephir-rs-${{ matrix.target }}
          path: artifacts/zephir-rs-${{ matrix.target }}
